_target_: pytorch_lightning.Trainer

gpus: 0
precision: 32

min_epochs: 1
max_epochs: 3

val_check_interval: 0.5

progress_bar_refresh_rate: 5
resume_from_checkpoint: null

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 1
