_target_: src.models.hf_model.SequenceClassificationTransformer

num_labels: ${datamodule.num_labels}
huggingface_model: "prajjwal1/bert-tiny"
learning_rate: 3e-5
batch_size: ${datamodule.batch_size}
loss_fn: "crossentropy"
use_bias_probs: False
