_target_: src.models.hf_model.SequenceClassificationTransformer

num_labels: ${datamodule.num_labels}
huggingface_model: "bert-base-uncased"
learning_rate: 2e-5
batch_size: ${datamodule.batch_size}
loss_fn: "crossentropy"
use_bias_probs: False
