_target_: src.models.hf_model.SequenceClassificationTransformer

num_labels: null # Override me in your experiment config!
huggingface_model: "bert-base-uncased"
learning_rate: 3e-5
batch_size: ${datamodule.batch_size}