# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: weak-ensembles
  # entity: ""  # set to name of your wandb team
  name: ${name} # Set to null (None) to let wandb add their funny random names
  save_dir: "."
  offline: False # set True to store all logs only locally
  id: null # pass correct id to resume experiment
  log_model: False
  prefix: ""
  job_type: "train"
  group: ""
  tags: []
