model_checkpoint:
  _target_: src.callbacks.hf_checkpoint.ModelCheckpointWithCompiling
  monitor: null # only save last epoch model
  save_top_k: 0 # only save last epoch model
  save_last: True # last epoch model
  verbose: False
  dirpath: "./" # save "last.ckpt" into the experiment directory
  
rich_progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar