_target_: src.datamodules.hf_datamodule.HFDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
dataset_folder: "mnli-tokenized"
tokenizer_name: ${model.huggingface_model}
batch_size: 128
num_workers: 8
pin_memory: True