_target_: src.datamodules.hf_bias_datamodule.HFBiasDataModule

dataset_name: glue
subdataset_name: mnli
num_labels: 3
tokenizer_name: ${model.huggingface_model}
sentence_1_name: premise
sentence_2_name: hypothesis
val_subset_name: "validation_matched"
test_subset_name: "test_matched"
batch_size: 128
num_workers: 8
pin_memory: True

bias_path: mnli_shallow_2K_fixed.json