_target_: src.datamodules.mnli_datamodule.MNLIDataModule

num_labels: 3
data_path: "/home/meissner/shortcut-pruning/data/mnli/"
sentence_1_name: "premise"
sentence_2_name: "hypothesis"
tokenizer_name: ${model.huggingface_model}
batch_size: 32
num_workers: 8
pin_memory: True
