_target_: src.datamodules.fever_datamodule.QQPDataModule

num_labels: 2
data_path: "/home/meissner/shortcut-pruning/data/paws/paws_qqp/"
tokenizer_name: ${model.huggingface_model}
sentence_1_name: question1
sentence_2_name: question2
batch_size: 32
num_workers: 8
pin_memory: True
