_target_: src.datamodules.squad_datamodule.SquadDatamodule

tokenizer_name: ${model.huggingface_model}
output_dir: "."
n_best_size: 20
max_length: 384
doc_stride: 128
max_answer_length: 30
version_2_with_negative: False
null_score_diff_threshold: .0
batch_size: 16
num_workers: 8
pin_memory: True
