# @package _global_

# run in debug mode with:
# `python run.py debug=default`

defaults:
  - override /trainer: debug.yaml
  - override /logger: none.yaml
  - override /callbacks: none.yaml
  - override /log_dir: debug.yaml

debug_mode: True

hydra:
  # sets level of all command line loggers to 'DEBUG'
  # verbose: True Something causes a huge amount of log output when I use this...

  # https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
  # use this to set level of only chosen command line loggers to 'DEBUG'
  verbose: [src.train, src.utils.utils]

# disable rich config printing, since it will be already printed by hydra when `verbose: True`
# print_config: False
